<?php

/**
 * @file
 * Primary module hooks for paragraphs_gridstack module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function paragraphs_gridstack_help($route_name, RouteMatchInterface $route_match) {
  // @TODO Add the help information about paragraphs gridstack module.
}

/**
 * Implements hook_preprocess_paragraph().
 */
function paragraphs_gridstack_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['elements']['#paragraph'];

  // @TODO Attach to the paragraphs with enabled gridstack behavior.
  // @TODO Probably better to move into behavior plugin.
  // @TODO Pass properties of the optionset to the JS.
  if ($paragraph->bundle() === 'gridstack') {
    $variables['#attached']['library'][] = 'paragraphs_gridstack/paragraphs_gridstack';
  }
}
