<?php

/**
 * @file
 * Primary module hooks for paragraphs_gridstack module.
 */

/**
 * Implements hook_preprocess_paragraph().
 */
function paragraphs_gridstack_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['elements']['#paragraph'];

  // @TODO Attach to the paragraphs with enabled gridstack behavior.
  // @TODO Probably better to move into behavior plugin.
  // @TODO Pass properties of the optionset to the JS.
  if ($paragraph->bundle() === 'gridstack') {
    $variables['#attached']['library'][] = 'paragraphs_gridstack/paragraphs_gridstack';
  }
}

/**
 * Test service 'paragraphs_gridstack.manager'.
 */
function paragraphs_gridstack_page_attachments_alter(array &$attachments) {
  /** @var Drupal\paragraphs_gridstack\ParagraphsGridstackManager $gridstack_manager */
  $gridstack_manager = \Drupal::service('paragraphs_gridstack.manager');
  $list = $gridstack_manager->listAll();
  $default = $gridstack_manager->get();

}
